plugins:
    # 参数: https://github.com/postcss/autoprefixer#features
    autoprefixer: {}

    # 注意: 如果你使用了某些处于不稳定状态的特性（比如nesting-rules），那么你就有重写的风险
    # 特性: 你可以从这里找到该插件所支持的所有特性 https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/FEATURES.md
    postcss-preset-env: {}
